version: '3.8'

services:
  ai-agent-demo:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - OLLAMA_BASE_URL=http://ollama:11434
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DIFY_API_KEY=${DIFY_API_KEY}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ai-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - ai-network

  # 可选：Redis缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ai-network

volumes:
  ollama_data:
  redis_data:

networks:
  ai-network:
    driver: bridge 